import type { ResumeContent } from "../types/resume";

const fullstackResume: ResumeContent = {
  name: "Justice Abutu",
  position: "Senior Full-Stack / Product Engineer | Laravel, Vue.js, React, TypeScript",
  address: "Abuja, Nigeria",
  availability: "Open to remote employment and international contract roles",
  email: "justiceroyale1@gmail.com",
  phoneNumber: "+234 813 054 6010",
  phoneHref: "+2348130546010",
  linkedinUrl: "https://www.linkedin.com/in/justice-abutu-royale/",
  githubUrl: "https://github.com/justiceroyale1",
  managedCoUrl: "https://managedcohq.com/",
  summary:
    "Senior full-stack and product-focused software engineer with seven years of experience turning operational requirements into working web products. I build across Laravel, PHP, TypeScript, Node.js, Vue.js, and React, and I have owned features spanning discovery, architecture, APIs, database design, user interfaces, testing, deployment, and production support. My work has covered commerce, payments, identity verification, property management, construction, education, reporting, and multi-tenant business software. I work well in distributed teams and have collaborated remotely with colleagues in Nigeria, Kenya, the United Kingdom, and the United States.",
  skillCategories: [
    {
      name: "Product Engineering",
      skills: [
        "Feature discovery",
        "workflow modelling",
        "technical design",
        "product iteration",
        "stakeholder collaboration",
        "production support",
      ],
    },
    {
      name: "Backend",
      skills: [
        "PHP",
        "Laravel",
        "Node.js",
        "TypeScript",
        "JavaScript",
        "REST APIs",
        "Eloquent ORM",
        "authentication",
        "permissions",
        "webhooks",
        "queues",
        "payment integrations",
      ],
    },
    {
      name: "Frontend",
      skills: [
        "Vue.js",
        "Vue 3",
        "Nuxt.js",
        "React",
        "Pinia",
        "Tailwind CSS",
        "shadcn-vue",
        "Bootstrap",
        "Vuetify",
        "Blade",
        "Vite",
      ],
    },
    {
      name: "Data",
      skills: [
        "MySQL",
        "MariaDB",
        "PostgreSQL",
        "MongoDB",
        "Redis",
        "database transactions",
        "indexing",
        "query optimisation",
      ],
    },
    {
      name: "Architecture and Quality",
      skills: [
        "Modular monoliths",
        "microservices",
        "multi-tenant applications",
        "event-driven workflows",
        "audit logging",
        "PHPUnit",
        "Cypress",
        "unit testing",
        "feature testing",
        "integration testing",
        "static analysis",
        "code review",
      ],
    },
    {
      name: "Infrastructure and Delivery",
      skills: [
        "Docker",
        "Docker Compose",
        "GitHub Actions",
        "Jenkins",
        "CircleCI",
        "Nginx",
        "AWS EC2",
        "AWS S3",
        "Railway",
        "Cloudflare",
        "Heroku",
        "Laravel Horizon",
        "Supervisor",
      ],
    },
  ],
  experienceList: [
    {
      company: "Coamana",
      position: "Senior Full-Stack Engineer",
      location: "Abuja, Nigeria",
      website: "https://www.coamana.com/",
      duration: "November 2024 – June 2026",
      description:
        "Worked on AmanaMarket, a multi-country product used by traders, market leaders, enterprise users, and operations teams for commerce, finance, verification, payments, and logistics.",
      tasks: [
        "Contributed 1,396 commits across the Laravel backend, Vue.js frontend, APIs, database layer, automated tests, and deployment tooling between December 2024 and May 2026.",
        "Built end-to-end finance and order-management features, including APIs, dashboards, filters, reporting, and transaction analysis, contributing to a reported 40% reduction in order-processing time.",
        "Designed verification and KYC experiences for wholesalers, suppliers, retailers, market leaders, and enterprise users across different country requirements.",
        "Delivered repayment, dispute, commission, credit-limit, audit-log, and transaction-statistics workflows, including validation, permissions, transactional handling, tests, and user-facing interfaces.",
        "Expanded payments and commerce across Nigeria and Kenya through M-Pesa, Paystack, VBank, wallets, pay-on-delivery, and inter-market trading.",
        "Built administration and logistics features covering markets, members, fees, invitations, suspensions, providers, vehicles, routes, order coordination, and payouts.",
        "Created reusable Vue 3 and shadcn-vue components for dashboards, forms, modals, comboboxes, tooltips, and market switching.",
        "Improved product reliability through query logging, authorization safeguards, refactoring, CI stabilisation, and faster parallel test execution.",
      ],
    },
    {
      company: "KadMap",
      position: "Senior Full-Stack Developer",
      location: "Abuja, Nigeria",
      website: "https://www.kadmap.com/",
      duration: "August 2024 – November 2025",
      description:
        "Worked on an offline-first cloud-computing product that combined local infrastructure with centrally managed services.",
      tasks: [
        "Built Authentication and Directory services for users, organisations, workspaces, and resource access.",
        "Designed the device-onboarding flow from administrator configuration through device identity, workspace permissions, and token issuance.",
        "Contributed to activation, restoration, licensing, and organisational data workflows between local KadMap Data Machines and central services.",
        "Built KadMap Connect features for installation setup, subscriptions, add-ons, instalment payments, and support tickets.",
        "Connected the React interface to authentication and licensing services through Convex while keeping service responsibilities clear.",
      ],
    },
    {
      company: "New Avenue",
      position: "Full-Stack Developer",
      employmentType: "Contract",
      location: "New York, United States",
      website: "https://www.newavenuehomes.com/",
      duration: "November 2023 – February 2024",
      tasks: [
        "Redesigned invoicing workflows for a housing-operations platform, reducing processing errors by a reported 35%.",
        "Fixed defects in an automated scheduling system, improving resource allocation by a reported 50%.",
        "Built a budgeting module with real-time reporting.",
        "Integrated payment and email-campaign services and worked within the company’s in-house framework alongside a distributed team.",
      ],
    },
    {
      company: "XRadar360",
      position: "Full-Stack Developer",
      location: "Leicester, United Kingdom",
      duration: "January 2021 – September 2023",
      description:
        "Joined as a backend developer and gradually took ownership across the product stack.",
      tasks: [
        "Built project and work-package workflows for one-time and recurring construction tasks, each with independent budgets.",
        "Developed expert onboarding, verification, notifications, bidding, quotations, negotiation, and contract-award journeys.",
        "Implemented multi-currency escrow that held funds until work was completed, inspected, and approved.",
        "Built progress reporting with geo-tagged media, plus complaint, dispute, and reconciliation workflows.",
        "Supported early product delivery and maintenance through Heroku-based deployments.",
      ],
    },
    {
      company: "Truelandlord",
      position: "Full-Stack Developer",
      employmentType: "Contract",
      location: "Abuja, Nigeria",
      website: "https://truelandlord.com/",
      duration: "March 2022 – October 2022",
      tasks: [
        "Built property-management workflows for owners, managers, and prospective tenants.",
        "Developed contract management with digital signatures, multi-factor authentication, and identity verification.",
        "Built search and recommendation features and optimised queries, reducing response time by a reported 60%.",
        "Implemented responsive interfaces across the property discovery and management experience.",
      ],
    },
    {
      company: "SchoolShell",
      position: "Full-Stack Developer",
      location: "Abuja, Nigeria",
      website: "https://schoolshell.com/",
      duration: "April 2019 – August 2020",
      tasks: [
        "Built inventory-management and reporting workflows for the Federal Judicial Service Commission.",
        "Developed student admission, document verification, automated report cards, and school communication features.",
        "Worked across backend, frontend, and database development during the early stage of my engineering career.",
      ],
    },
  ],
  independentProjectList: [
    {
      name: "ManagedCo",
      role: "Founder and Lead Engineer",
      duration: "January 2026 - Present",
      website: "https://managedcohq.com/",
      description:
        "A multi-tenant operations platform that helps small businesses manage orders, inventory, customers, follow-up, and online storefronts from one system.",
      tasks: [
        "Took the product from business discovery and workflow definition through architecture, interface design, implementation, deployment, and production support.",
        "Built tenant-aware authentication, permissions, order workflows, stock management, customer records, storefronts, and reporting.",
        "Developed the Laravel backend and Vue-based interface, including operational dashboards and reusable application components.",
        "Set up Redis-backed queues, separate application and worker services, S3-compatible storage, CI/CD, and environment-specific deployments.",
        "Resolved production issues involving session cookies, workers, Redis, DNS, runtime configuration, and cross-origin requests.",
        "Continued refining the product through direct conversations with small businesses about stock, order tracking, customer follow-up, and day-to-day visibility.",
      ],
    },
  ],
  educationList: [
    {
      title: "Bachelor of Science in Computer Science",
      institution: "Federal University of Lafia",
      location: "Nasarawa, Nigeria",
      duration: "2013 – 2017",
    },
  ],
  certificationList: [
    {
      title: "Senior Full-Stack Software Engineering Certification",
      issuer: "micro1",
      date: "July 2026",
      details:
        "Assessment areas included core PHP, backend development, APIs, web architecture, databases, performance, scalability, and production engineering.",
    },
  ],
};

export const useFullstackResume = () => fullstackResume;
